import {
    Activity,
    Download,
    FileClock,
    FileWarning,
    KeyRound,
    Lock,
    LogIn,
    LogOut,
    ShieldAlert,
    ShieldCheck,
    ShieldOff,
    Share2,
    Trash2,
    Upload,
    type LucideIcon,
} from 'lucide-react';

type AuditBadge = {
    icon: LucideIcon;
    label: string;
    className: string;
};

export const AUDIT_ACTION_BADGES: Record<string, AuditBadge> = {
    login_success: { icon: LogIn, label: 'Login success', className: 'border-transparent bg-green-500/15 text-green-700 dark:text-green-400' },
    document_uploaded: { icon: Upload, label: 'Uploaded', className: 'border-transparent bg-green-500/15 text-green-700 dark:text-green-400' },
    document_restored: { icon: Upload, label: 'Restored', className: 'border-transparent bg-green-500/15 text-green-700 dark:text-green-400' },
    data_export_requested: { icon: Download, label: 'Data export requested', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    document_version_uploaded: { icon: Upload, label: 'Version replaced', className: 'border-transparent bg-green-500/15 text-green-700 dark:text-green-400' },
    document_version_restored: { icon: Activity, label: 'Version restored', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    '2fa_enabled': { icon: ShieldCheck, label: '2FA enabled', className: 'border-transparent bg-green-500/15 text-green-700 dark:text-green-400' },
    two_factor_enabled: { icon: ShieldCheck, label: '2FA enabled', className: 'border-transparent bg-green-500/15 text-green-700 dark:text-green-400' },
    '2fa_verified': { icon: ShieldCheck, label: '2FA verified', className: 'border-transparent bg-green-500/15 text-green-700 dark:text-green-400' },
    recovery_code_used: { icon: ShieldCheck, label: 'Recovery code used', className: 'border-transparent bg-green-500/15 text-green-700 dark:text-green-400' },
    document_shared: { icon: Share2, label: 'Shared', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    signed_url_generated: { icon: Share2, label: 'Share link generated', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    signed_url_accessed: { icon: Share2, label: 'Share link accessed', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    audit_integrity_check: { icon: ShieldCheck, label: 'Integrity check', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    ip_rule_added: { icon: ShieldCheck, label: 'IP rule added', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    document_downloaded: { icon: Download, label: 'Downloaded', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    document_starred: { icon: Activity, label: 'Starred', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    document_unstarred: { icon: Activity, label: 'Unstarred', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    bulk_download: { icon: Download, label: 'Bulk download', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    logout: { icon: LogOut, label: 'Logout', className: 'border-transparent bg-muted text-muted-foreground' },
    '2fa_disabled': { icon: ShieldOff, label: '2FA disabled', className: 'border-transparent bg-muted text-muted-foreground' },
    two_factor_disabled: { icon: ShieldOff, label: '2FA disabled', className: 'border-transparent bg-muted text-muted-foreground' },
    request: { icon: Activity, label: 'Request', className: 'border-transparent bg-muted text-muted-foreground' },
    document_deleted: { icon: Trash2, label: 'Deleted', className: 'border-transparent bg-muted text-muted-foreground' },
    profile_updated: { icon: Activity, label: 'Profile updated', className: 'border-transparent bg-muted text-muted-foreground' },
    bulk_delete: { icon: Trash2, label: 'Bulk delete', className: 'border-transparent bg-muted text-muted-foreground' },
    document_permanently_deleted: { icon: Trash2, label: 'Permanently deleted', className: 'border-transparent bg-muted text-muted-foreground' },
    trash_emptied: { icon: Trash2, label: 'Trash emptied', className: 'border-transparent bg-muted text-muted-foreground' },
    auto_purged: { icon: Trash2, label: 'Auto purged', className: 'border-transparent bg-muted text-muted-foreground' },
    user_activated: { icon: Activity, label: 'User activated', className: 'border-transparent bg-muted text-muted-foreground' },
    user_deactivated: { icon: Activity, label: 'User deactivated', className: 'border-transparent bg-muted text-muted-foreground' },
    user_role_changed: { icon: Activity, label: 'Role changed', className: 'border-transparent bg-muted text-muted-foreground' },
    two_factor_deadline_set: { icon: ShieldAlert, label: '2FA deadline set', className: 'border-transparent bg-amber-500/15 text-amber-600 dark:text-amber-400' },
    password_changed: { icon: KeyRound, label: 'Password changed', className: 'border-transparent bg-amber-500/15 text-amber-600 dark:text-amber-400' },
    google_oauth_login: { icon: LogIn, label: 'Google Sign-In', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    google_oauth_linked: { icon: ShieldCheck, label: 'Google Linked', className: 'border-transparent bg-green-500/15 text-green-700 dark:text-green-400' },
    google_oauth_unlinked: { icon: ShieldOff, label: 'Google Unlinked', className: 'border-transparent bg-amber-500/15 text-amber-600 dark:text-amber-400' },
    google_oauth_denied: { icon: Activity, label: 'Google OAuth Denied', className: 'border-transparent bg-muted text-muted-foreground' },
    email_verified: { icon: ShieldCheck, label: 'Email Verified', className: 'border-transparent bg-green-500/15 text-green-700 dark:text-green-400' },
    login_failed: { icon: LogIn, label: 'Login failed', className: 'border-transparent bg-destructive/15 text-destructive' },
    google_oauth_login_failed: { icon: ShieldAlert, label: 'Google Sign-In Failed', className: 'border-transparent bg-destructive/15 text-destructive' },
    google_oauth_link_failed: { icon: ShieldAlert, label: 'Google Link Failed', className: 'border-transparent bg-destructive/15 text-destructive' },
    login_blocked_inactive: { icon: Lock, label: 'Login blocked', className: 'border-transparent bg-destructive/15 text-destructive' },
    '2fa_failed': { icon: ShieldAlert, label: '2FA failed', className: 'border-transparent bg-destructive/15 text-destructive' },
    recovery_code_failed: { icon: ShieldAlert, label: 'Recovery code failed', className: 'border-transparent bg-destructive/15 text-destructive' },
    account_locked: { icon: Lock, label: 'Account locked', className: 'border-transparent bg-destructive/15 text-destructive' },
    access_blocked_ip: { icon: ShieldAlert, label: 'IP blocked', className: 'border-transparent bg-destructive/15 text-destructive' },
    account_deletion_requested: { icon: ShieldAlert, label: 'Deletion requested', className: 'border-transparent bg-destructive/15 text-destructive' },
    account_deletion_cancelled: { icon: ShieldCheck, label: 'Deletion cancelled', className: 'border-transparent bg-blue-500/15 text-blue-600 dark:text-blue-400' },
    account_deletion_executed: { icon: Trash2, label: 'Deletion executed', className: 'border-transparent bg-destructive/15 text-destructive' },
    malware_detected: { icon: FileWarning, label: 'Malware detected', className: 'border-transparent bg-destructive/15 text-destructive' },
    document_scan_blocked: { icon: FileWarning, label: 'Malware blocked', className: 'border-transparent bg-destructive/15 text-destructive' },
    integrity_violation: { icon: ShieldAlert, label: 'Integrity failed', className: 'border-transparent bg-destructive/15 text-destructive' },
    '2fa_corrupt_reset': { icon: ShieldAlert, label: '2FA reset', className: 'border-transparent bg-destructive/15 text-destructive' },
    bot_detected: { icon: ShieldAlert, label: 'Bot detected', className: 'border-transparent bg-destructive/15 text-destructive' },
    share_revoked: { icon: Share2, label: 'Share revoked', className: 'border-transparent bg-destructive/15 text-destructive' },
    pwned_password_rejected: { icon: ShieldAlert, label: 'Pwned password', className: 'border-transparent bg-destructive/15 text-destructive' },
    session_revoked: { icon: FileClock, label: 'Session revoked', className: 'border-transparent bg-destructive/15 text-destructive' },
    session_terminated: { icon: FileClock, label: 'Session terminated', className: 'border-transparent bg-destructive/15 text-destructive' },
    all_sessions_terminated: { icon: FileClock, label: 'All sessions terminated', className: 'border-transparent bg-destructive/15 text-destructive' },
    ip_rule_removed: { icon: ShieldAlert, label: 'IP rule removed', className: 'border-transparent bg-destructive/15 text-destructive' },
    recovery_codes_regenerated: { icon: KeyRound, label: 'Recovery codes regenerated', className: 'border-transparent bg-amber-500/15 text-amber-600 dark:text-amber-400' },
};

export function getAuditActionBadge(action: string): AuditBadge {
    return AUDIT_ACTION_BADGES[action] ?? {
        icon: Activity,
        label: action.replace(/_/g, ' '),
        className: 'border-transparent bg-muted text-muted-foreground',
    };
}
